# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k8AXUOdIAf0omvvPh3lxZ9TwvLxOBqH-
"""

# ==========================================
# Student Performance Prediction System
# Part 1: Dataset Generation
# ==========================================

import numpy as np
import pandas as pd

# Set random seed for reproducibility
np.random.seed(42)

# Number of student records
num_students = 2500

# -------------------------------
# Generate Student Data
# -------------------------------

student_id = np.arange(1, num_students + 1)

age = np.random.randint(17, 24, num_students)

gender = np.random.choice(
    ["Male", "Female"],
    num_students
)

attendance = np.random.randint(
    50, 101,
    num_students
)

study_hours = np.random.randint(
    1, 31,
    num_students
)

assignment = np.random.randint(
    40, 101,
    num_students
)

previous_score = np.random.randint(
    35, 100,
    num_students
)

participation = np.random.randint(
    1, 11,
    num_students
)

activities = np.random.choice(
    ["Yes", "No"],
    num_students
)

internet = np.random.choice(
    ["Yes", "No"],
    num_students,
    p=[0.85, 0.15]
)

parent_education = np.random.choice(
    ["High School", "Graduate", "Postgraduate"],
    num_students,
    p=[0.4, 0.4, 0.2]
)

# -------------------------------
# Create Final Exam Score
# -------------------------------

final_score = (
      attendance * 0.20
    + study_hours * 1.20
    + assignment * 0.20
    + previous_score * 0.35
    + participation * 2
)

# Bonus marks

final_score += np.where(activities == "Yes", 3, 0)
final_score += np.where(internet == "Yes", 2, 0)

final_score += np.where(parent_education == "Graduate", 2, 0)
final_score += np.where(parent_education == "Postgraduate", 5, 0)

# Add random noise

noise = np.random.normal(0, 5, num_students)

final_score = final_score + noise

# Keep score between 0 and 100

final_score = np.clip(final_score, 0, 100)

# Round values

final_score = np.round(final_score, 2)

# -------------------------------
# Create DataFrame
# -------------------------------

student_df = pd.DataFrame({

    "StudentID": student_id,

    "Age": age,

    "Gender": gender,

    "AttendancePercentage": attendance,

    "StudyHoursPerWeek": study_hours,

    "AssignmentCompletionRate": assignment,

    "PreviousExamScore": previous_score,

    "ParticipationScore": participation,

    "ExtracurricularActivities": activities,

    "InternetAccessAtHome": internet,

    "ParentEducationLevel": parent_education,

    "FinalExamScore": final_score

})

# -------------------------------
# Save Dataset
# -------------------------------

student_df.to_csv(
    "student_performance_dataset.csv",
    index=False
)

print("Dataset created successfully!")

print()

print(student_df.head())

print()

print("Shape of Dataset:")

print(student_df.shape)

print()

print("Column Names:")

print(student_df.columns)